export {default as BackgroundTop} from './BackgroundTop'
export {default as GiftCurrent} from './GiftCurrent'
export {default as ImageCenter} from './ImageCenter'
export {default as FeaturedProduct} from './FeaturedProduct'
export {default as HotPromotion} from './HotPromotion'
export {default as ForYou} from './ForYou'
export {default as Trademark} from './TrademarkHot'
export {default as Blog} from './Blog'